#!/usr/bin/env bash
# Installs HAProxy version 2.6 with the following configurations:

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.6
apt-get update
apt-get install -y haproxy=2.6.\*

echo "ENABLED=1" >> /etc/default/haproxy

sed -i '/504.http/a \\nlisten http-in\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\tserver 39159-web-01 54.152.232.124:80 check\n\tserver 39159-web-02 34.202.157.225:80 check' /etc/haproxy/haproxy.cfg


service haproxy start

