#!/usr/bin/env bash

# Find the PID of the Gunicorn master process
PID=$(pgrep gunicorn)

# If the master process is running, gracefully reload it
if [ -n "$PID" ]; then
    echo "Reloading Gunicorn gracefully"
    kill -HUP "$PID"
else
    echo "Gunicorn is not running"
fi

